site_name: 'test3'
site_description: 'Main documentation for the test3'
repo_url: https://github.com/mallama-org/test3
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'docs/index.md'